# Generated by Django 5.2.7 on 2025-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartitem_created_at_cartitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
